language: python
python: '3.5'
branches:
  only:
  - content
before_install:
- openssl aes-256-cbc -K $encrypted_7ec5ed03f863_key -iv $encrypted_7ec5ed03f863_iv
  -in deploy_key.enc -out deploy_key -d
install:
- pip install -r requirements.txt
script:
- make publish
after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- make github
