language: python
dist: xenial
python: '3.7'
branches:
  only:
  - content
before_install:
- openssl aes-256-cbc -K $encrypted_7ec5ed03f863_key -iv $encrypted_7ec5ed03f863_iv
  -in deploy_key.enc -out deploy_key -d
install:
- pipenv install
script:
- pipenv run make publish
after_success:
- chmod 600 deploy_key
- mv deploy_key ~/.ssh/id_rsa
#- pipenv run make github
